# Generated by Django 3.2.6 on 2021-09-16 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customer_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.region'),
        ),
    ]
