# Generated by Django 3.2.6 on 2021-09-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customer_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
